version: "3.9"

services:
  db:
    image: postgres:15
    container_name: global
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: database_global
    ports:
      - "5433:5432" # local:contendor
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
